package constants.submodules;

import constants.PurchasesConstants;

/**
 * @author german.massello
 *
 */
public interface RequisitionConstants extends PurchasesConstants {
	
	String ADVANCE_FILTERS_GROUP = "ADVANCE_FILTERS_GROUP";	
	String ADVANCE_FILTERS_FALSE = "ADVANCE_FILTERS_FALSE";	
	String ADVANCE_FILTERS_REQUESTER = "ADVANCE_FILTERS_REQUESTER";	
	
	String REQUISITION_STATE = "REQUISITION";
	String EMPTY_REQUISITION_STATE = "";
	String DRAFT_REQUISITION_STATE = "DRAFT";
	
	String EMPTY_REQUISITION_STATUS = "";
	String RECEPTION_COMPLETE_STATUS_DB = "Reception completed";
	String PARTIALLY_PENDING_STATUS_DB = "Partially pending";
	String PENDING_APPROVAL_STATUS_DB = "Pending for approval";
	String APPROVED_STATUS_DB = "Approved";
	String PARTIALY_REJECTED_STATUS_DB = "Partially rejected";
	String REJECTED_BY_APPROVER_STATUS_DB = "Rejected by approver";
	String REJECTED_BY_PURCHASER_STATUS_DB = "Rejected by purchaser";
	String PO_NUMBER_CREATED_STATUS_DB = "PO number created";
	String RECEPTION_PENDING_STATUS_DB= "Reception pending";
	
	String RECEPTION_COMPLETE_STATUS_REST = "RECEPTION_COMPLETED";
	String PARTIALLY_PENDING_STATUS_REST = "PARTIALLY_PENDING";
	String PENDING_APPROVAL_STATUS_REST = "PENDING_FOR_APPROVAL";
	String APPROVED_STATUS_REST = "APPROVED";
	String PARTIALY_REJECTED_STATUS_REST = "PARTIALY_REJECTED";
	String REJECTED_BY_APPROVER_STATUS_REST = "REJECTED_BY_APPROVER";
	String REJECTED_BY_PURCHASER_STATUS_REST = "REJECTED_BY_PURCHASER";
	String PO_NUMBER_CREATED_STATUS_REST = "PO_NUMBER_CREATED";
	String RECEPTION_PENDING_STATUS_REST= "RECEPTION_PENDING";
}
